var searchData=
[
  ['cadfael_0',['Version 0.1 - Cadfael',['../changelog.html#autotoc_md26',1,'']]],
  ['cartesian_5fproduct_1',['cartesian_product',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['cartesian_5fproduct_3c_20l_2c_20l_20_3e_2',['cartesian_product&lt; L, L &gt;',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['case_3',['Specify a Test Case',['../tts101.html#tuto-test-case',1,'']]],
  ['cases_4',['Cost of test cases',['../compile-time.html#compile-time-comparison-cases',1,'']]],
  ['change_20log_5',['Change Log',['../changelog.html',1,'']]],
  ['changed_6',['Changed',['../changelog.html#autotoc_md1',1,'What&apos;s Changed'],['../changelog.html#autotoc_md5',1,'What&apos;s Changed'],['../changelog.html#autotoc_md12',1,'What&apos;s Changed'],['../changelog.html#autotoc_md18',1,'What&apos;s Changed']]],
  ['changes_7',['Breaking Changes',['../changelog.html#autotoc_md2',1,'']]],
  ['checklist_20for_20a_20new_20header_8',['Checklist for a new header',['../compile-time.html#compile-time-checklist',1,'']]],
  ['classes_9',['Output Sink Classes',['../group__tools-sinks.html',1,'']]],
  ['clear_10',['clear',['../structtts_1_1json__sink.html#a1cc5ede76e87da13226b9d41c3e656fd',1,'tts::json_sink::clear()'],['../structtts_1_1junit__sink.html#a087cc19fede7a034228f51ee60453b96',1,'tts::junit_sink::clear()'],['../structtts_1_1tap__sink.html#adf7651758a0da8c0e813b53dacec8356',1,'tts::tap_sink::clear()'],['../structtts_1_1gathering__sink.html#a6c8880d803778193c99a7b95d877a1d1',1,'tts::gathering_sink::clear()']]],
  ['cleared_20headers_11',['Measured and cleared headers',['../compile-time.html#compile-time-fine',1,'']]],
  ['cli_20flag_12',['CLI Flag',['../output-sinks.html#autotoc_md49',1,'CLI Flag'],['../output-sinks.html#autotoc_md54',1,'CLI Flag'],['../output-sinks.html#autotoc_md59',1,'CLI Flag'],['../output-sinks.html#autotoc_md66',1,'CLI Flag'],['../output-sinks.html#autotoc_md72',1,'CLI Flag']]],
  ['cmake_20fetchcontent_13',['CMake FetchContent',['../setup.html#setup-fetchcontent',1,'']]],
  ['colorized_5fsink_14',['colorized_sink',['../structtts_1_1colorized__sink.html',1,'tts']]],
  ['command_20line_20interface_15',['Command Line Interface',['../cli.html',1,'']]],
  ['comparison_16',['Comparison',['../customize.html#autotoc_md37',1,'Absolute Comparison'],['../customize.html#autotoc_md35',1,'IEEE Comparison'],['../customize.html#autotoc_md36',1,'Relative Comparison']]],
  ['comparison_17',['comparison',['../structtts_1_1comparison.html',1,'tts']]],
  ['comparison_20utilities_18',['Comparison Utilities',['../group__tools-comparison.html',1,'']]],
  ['compile_20time_20discipline_19',['Compile-Time Discipline',['../compile-time.html',1,'']]],
  ['compilers_20',['Supported Compilers',['../index.html#autotoc_md40',1,'']]],
  ['computing_20ulp_21',['Computing ULP',['../rationale.html#ulp-computing',1,'']]],
  ['configuration_20utilities_22',['Configuration Utilities',['../group__tools-config.html',1,'']]],
  ['content_23',['content',['../structtts_1_1gathering__sink.html#a9d2a181f4d6a9d95c9e8ff008b0120d2',1,'tts::gathering_sink']]],
  ['contributors_24',['New Contributors',['../changelog.html#autotoc_md9',1,'']]],
  ['control_25',['Execution Control',['../cli.html#autotoc_md31',1,'']]],
  ['conversion_26',['conversion',['../structtts_1_1conversion.html',1,'tts']]],
  ['convert_5fas_27',['convert_as',['../group__tools-generators-custom.html#gaab0ecf513cd7c017ecbb918bcf60f091',1,'tts']]],
  ['cordelia_20gray_28',['Version 2.1 - Cordelia Gray',['../changelog.html#autotoc_md17',1,'']]],
  ['cost_29',['cost',['../compile-time.html#compile-time-cost',1,'Avoided headers and their cost'],['../compile-time.html#compile-time-comparison-include',1,'Minimal include cost']]],
  ['cost_20and_20crossings_30',['Fixed cost and crossings',['../compile-time.html#compile-time-comparison-fits',1,'']]],
  ['cost_20of_20a_20test_20suite_31',['Include cost of a test suite',['../compile-time.html#compile-time-why',1,'']]],
  ['cost_20of_20test_20cases_32',['Cost of test cases',['../compile-time.html#compile-time-comparison-cases',1,'']]],
  ['cpm_33',['Setup with CPM',['../setup.html#setup-cpm',1,'']]],
  ['crashed_20and_20stuck_20runs_34',['Crashed and Stuck Runs',['../customize.html#customize-abort',1,'']]],
  ['crossings_35',['Fixed cost and crossings',['../compile-time.html#compile-time-comparison-fits',1,'']]],
  ['customization_20points_36',['Customization Points',['../group__customization-points.html',1,'Customization Points'],['../group__tools-generators-custom.html',1,'Data Generators Customization Points']]],
  ['customizing_20tts_20behaviour_37',['Customizing TTS Behaviour',['../customize.html',1,'']]]
];
