var searchData=
[
  ['cadfael_0',['Version 0.1 - Cadfael',['../changelog.html#autotoc_md22',1,'']]],
  ['cartesian_5fproduct_1',['cartesian_product',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['cartesian_5fproduct_3c_20l_2c_20l_20_3e_2',['cartesian_product&lt; L, L &gt;',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['case_3',['Specify a Test Case',['../tts101.html#tuto-test-case',1,'']]],
  ['change_20log_4',['Change Log',['../changelog.html',1,'']]],
  ['changed_5',['Changed',['../changelog.html#autotoc_md1',1,'What&apos;s Changed'],['../changelog.html#autotoc_md8',1,'What&apos;s Changed'],['../changelog.html#autotoc_md14',1,'What&apos;s Changed']]],
  ['classes_6',['Output Sink Classes',['../group__tools-sinks.html',1,'']]],
  ['clear_7',['clear',['../structtts_1_1json__sink.html#a1cc5ede76e87da13226b9d41c3e656fd',1,'tts::json_sink::clear()'],['../structtts_1_1tap__sink.html#adf7651758a0da8c0e813b53dacec8356',1,'tts::tap_sink::clear()'],['../structtts_1_1gathering__sink.html#a6c8880d803778193c99a7b95d877a1d1',1,'tts::gathering_sink::clear()']]],
  ['cli_20flag_8',['CLI Flag',['../output-sinks.html#autotoc_md42',1,'CLI Flag'],['../output-sinks.html#autotoc_md47',1,'CLI Flag'],['../output-sinks.html#autotoc_md52',1,'CLI Flag'],['../output-sinks.html#autotoc_md59',1,'CLI Flag']]],
  ['cmake_20fetchcontent_9',['CMake FetchContent',['../setup.html#setup-fetchcontent',1,'']]],
  ['codebase_10',['Precedent in this codebase',['../compile-time.html#compile-time-precedent',1,'']]],
  ['colorized_5fsink_11',['colorized_sink',['../structtts_1_1colorized__sink.html',1,'tts']]],
  ['command_20line_20interface_12',['Command Line Interface',['../cli.html',1,'']]],
  ['comparison_13',['Comparison',['../customize.html#autotoc_md33',1,'Absolute Comparison'],['../customize.html#autotoc_md31',1,'IEEE Comparison'],['../customize.html#autotoc_md32',1,'Relative Comparison']]],
  ['compile_20time_20discipline_14',['Compile-Time Discipline',['../compile-time.html',1,'']]],
  ['compilers_15',['Supported Compilers',['../index.html#autotoc_md35',1,'']]],
  ['computing_20ulp_16',['Computing ULP',['../rationale.html#ulp-computing',1,'']]],
  ['configuration_20utilities_17',['Configuration Utilities',['../group__tools-config.html',1,'']]],
  ['content_18',['content',['../structtts_1_1gathering__sink.html#a9d2a181f4d6a9d95c9e8ff008b0120d2',1,'tts::gathering_sink']]],
  ['contributors_19',['New Contributors',['../changelog.html#autotoc_md5',1,'']]],
  ['control_20',['Execution Control',['../cli.html#autotoc_md27',1,'']]],
  ['convert_5fas_21',['convert_as',['../group__tools-generators-custom.html#gaab0ecf513cd7c017ecbb918bcf60f091',1,'tts']]],
  ['cordelia_20gray_22',['Version 2.1 - Cordelia Gray',['../changelog.html#autotoc_md13',1,'']]],
  ['cost_23',['Headers we avoid, and what they cost',['../compile-time.html#compile-time-cost',1,'']]],
  ['costs_20if_20you_20ever_20need_20one_20anyway_24',['What it costs if you ever need one anyway',['../compile-time.html#compile-time-hypothetical',1,'']]],
  ['cpm_25',['Setup with CPM',['../setup.html#setup-cpm',1,'']]],
  ['customization_20points_26',['Customization Points',['../group__customization-points.html',1,'Customization Points'],['../group__tools-generators-custom.html',1,'Data Generators Customization Points']]],
  ['customizing_20tts_20behaviour_27',['Customizing TTS Behaviour',['../customize.html',1,'']]]
];
