var searchData=
[
  ['cadfael_0',['Version 0.1 - Cadfael',['../changelog.html#autotoc_md26',1,'']]],
  ['cartesian_5fproduct_1',['cartesian_product',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['cartesian_5fproduct_3c_20l_2c_20l_20_3e_2',['cartesian_product&lt; L, L &gt;',['../structtts_1_1cartesian__product.html',1,'tts']]],
  ['case_3',['Specify a Test Case',['../tts101.html#tuto-test-case',1,'']]],
  ['change_20log_4',['Change Log',['../changelog.html',1,'']]],
  ['changed_5',['Changed',['../changelog.html#autotoc_md1',1,'What&apos;s Changed'],['../changelog.html#autotoc_md5',1,'What&apos;s Changed'],['../changelog.html#autotoc_md12',1,'What&apos;s Changed'],['../changelog.html#autotoc_md18',1,'What&apos;s Changed']]],
  ['changes_6',['Breaking Changes',['../changelog.html#autotoc_md2',1,'']]],
  ['classes_7',['Output Sink Classes',['../group__tools-sinks.html',1,'']]],
  ['clear_8',['clear',['../structtts_1_1json__sink.html#a1cc5ede76e87da13226b9d41c3e656fd',1,'tts::json_sink::clear()'],['../structtts_1_1junit__sink.html#a087cc19fede7a034228f51ee60453b96',1,'tts::junit_sink::clear()'],['../structtts_1_1tap__sink.html#adf7651758a0da8c0e813b53dacec8356',1,'tts::tap_sink::clear()'],['../structtts_1_1gathering__sink.html#a6c8880d803778193c99a7b95d877a1d1',1,'tts::gathering_sink::clear()']]],
  ['cli_20flag_9',['CLI Flag',['../output-sinks.html#autotoc_md49',1,'CLI Flag'],['../output-sinks.html#autotoc_md54',1,'CLI Flag'],['../output-sinks.html#autotoc_md59',1,'CLI Flag'],['../output-sinks.html#autotoc_md66',1,'CLI Flag'],['../output-sinks.html#autotoc_md72',1,'CLI Flag']]],
  ['cmake_20fetchcontent_10',['CMake FetchContent',['../setup.html#setup-fetchcontent',1,'']]],
  ['codebase_11',['Precedent in this codebase',['../compile-time.html#compile-time-precedent',1,'']]],
  ['colorized_5fsink_12',['colorized_sink',['../structtts_1_1colorized__sink.html',1,'tts']]],
  ['command_20line_20interface_13',['Command Line Interface',['../cli.html',1,'']]],
  ['comparison_14',['Comparison',['../customize.html#autotoc_md37',1,'Absolute Comparison'],['../customize.html#autotoc_md35',1,'IEEE Comparison'],['../customize.html#autotoc_md36',1,'Relative Comparison']]],
  ['comparison_15',['comparison',['../structtts_1_1comparison.html',1,'tts']]],
  ['comparison_20utilities_16',['Comparison Utilities',['../group__tools-comparison.html',1,'']]],
  ['compile_20time_20discipline_17',['Compile-Time Discipline',['../compile-time.html',1,'']]],
  ['compilers_18',['Supported Compilers',['../index.html#autotoc_md40',1,'']]],
  ['computing_20ulp_19',['Computing ULP',['../rationale.html#ulp-computing',1,'']]],
  ['configuration_20utilities_20',['Configuration Utilities',['../group__tools-config.html',1,'']]],
  ['content_21',['content',['../structtts_1_1gathering__sink.html#a9d2a181f4d6a9d95c9e8ff008b0120d2',1,'tts::gathering_sink']]],
  ['contributors_22',['New Contributors',['../changelog.html#autotoc_md9',1,'']]],
  ['control_23',['Execution Control',['../cli.html#autotoc_md31',1,'']]],
  ['conversion_24',['conversion',['../structtts_1_1conversion.html',1,'tts']]],
  ['convert_5fas_25',['convert_as',['../group__tools-generators-custom.html#gaab0ecf513cd7c017ecbb918bcf60f091',1,'tts']]],
  ['cordelia_20gray_26',['Version 2.1 - Cordelia Gray',['../changelog.html#autotoc_md17',1,'']]],
  ['cost_27',['Headers we avoid, and what they cost',['../compile-time.html#compile-time-cost',1,'']]],
  ['costs_20if_20you_20ever_20need_20one_20anyway_28',['What it costs if you ever need one anyway',['../compile-time.html#compile-time-hypothetical',1,'']]],
  ['cpm_29',['Setup with CPM',['../setup.html#setup-cpm',1,'']]],
  ['crashed_20and_20stuck_20runs_30',['Crashed and Stuck Runs',['../customize.html#customize-abort',1,'']]],
  ['customization_20points_31',['Customization Points',['../group__customization-points.html',1,'Customization Points'],['../group__tools-generators-custom.html',1,'Data Generators Customization Points']]],
  ['customizing_20tts_20behaviour_32',['Customizing TTS Behaviour',['../customize.html',1,'']]]
];
