var searchData=
[
  ['template_20machinery_0',['Template machinery',['../compile-time.html#compile-time-comparison-types',1,'']]],
  ['test_20case_1',['Specify a Test Case',['../tts101.html#tuto-test-case',1,'']]],
  ['test_20cases_2',['Cost of test cases',['../compile-time.html#compile-time-comparison-cases',1,'']]],
  ['test_20libraries_3',['Other test libraries',['../compile-time.html#compile-time-comparison',1,'']]],
  ['test_20suite_4',['Include cost of a test suite',['../compile-time.html#compile-time-why',1,'']]],
  ['test_20system_5',['The Tiny Test System',['../index.html',1,'']]],
  ['testing_6',['Precision testing',['../rationale.html#ulp',1,'']]],
  ['testing_20macros_7',['Testing Macros',['../tts_reference.html#autotoc_md42',1,'Testing Macros'],['../tts101.html#tuto-macro',1,'Testing Macros']]],
  ['testing_20ulps_8',['Testing ULPs',['../rationale.html#ulp-testing',1,'']]],
  ['tests_20driver_9',['Tests Driver',['../customize.html#customize-driver',1,'']]],
  ['tests_20parameters_10',['Tests Parameters',['../cli.html#autotoc_md32',1,'']]],
  ['the_20source_11',['Install from the source',['../setup.html#setup-source',1,'']]],
  ['the_20tiny_20test_20system_12',['The Tiny Test System',['../index.html',1,'']]],
  ['their_20cost_13',['Avoided headers and their cost',['../compile-time.html#compile-time-cost',1,'']]],
  ['time_20discipline_14',['Compile-Time Discipline',['../compile-time.html',1,'']]],
  ['tiny_20test_20system_15',['The Tiny Test System',['../index.html',1,'']]],
  ['tools_20and_20helpers_16',['Tools and Helpers',['../tts_reference.html#autotoc_md43',1,'']]],
  ['tts_17',['TTS',['../compile-time.html#compile-time-headers',1,'Headers of TTS'],['../compile-time.html#compile-time-precedent',1,'Replacements written in TTS']]],
  ['tts_20behaviour_18',['Customizing TTS Behaviour',['../customize.html',1,'']]],
  ['tts_3a_3acolorized_5fsink_19',['tts::colorized_sink',['../output-sinks.html#autotoc_md46',1,'']]],
  ['tts_3a_3adiagnostics_5fsink_20',['tts::diagnostics_sink',['../output-sinks.html#autotoc_md56',1,'']]],
  ['tts_3a_3ajson_5fsink_21',['tts::json_sink',['../output-sinks.html#autotoc_md62',1,'']]],
  ['tts_3a_3ajunit_5fsink_22',['tts::junit_sink',['../output-sinks.html#autotoc_md68',1,'']]],
  ['tts_3a_3atap_5fsink_23',['tts::tap_sink',['../output-sinks.html#autotoc_md51',1,'']]],
  ['type_24',['Producing values of a user-defined type',['../customize.html#autotoc_md39',1,'']]]
];
