var searchData=
[
  ['cadfael_0',['Version 0.1 - Cadfael',['../changelog.html#autotoc_md26',1,'']]],
  ['case_1',['Specify a Test Case',['../tts101.html#tuto-test-case',1,'']]],
  ['cases_2',['Cost of test cases',['../compile-time.html#compile-time-comparison-cases',1,'']]],
  ['change_20log_3',['Change Log',['../changelog.html',1,'']]],
  ['changed_4',['Changed',['../changelog.html#autotoc_md1',1,'What&apos;s Changed'],['../changelog.html#autotoc_md5',1,'What&apos;s Changed'],['../changelog.html#autotoc_md12',1,'What&apos;s Changed'],['../changelog.html#autotoc_md18',1,'What&apos;s Changed']]],
  ['changes_5',['Breaking Changes',['../changelog.html#autotoc_md2',1,'']]],
  ['checklist_20for_20a_20new_20header_6',['Checklist for a new header',['../compile-time.html#compile-time-checklist',1,'']]],
  ['cleared_20headers_7',['Measured and cleared headers',['../compile-time.html#compile-time-fine',1,'']]],
  ['cli_20flag_8',['CLI Flag',['../output-sinks.html#autotoc_md49',1,'CLI Flag'],['../output-sinks.html#autotoc_md54',1,'CLI Flag'],['../output-sinks.html#autotoc_md59',1,'CLI Flag'],['../output-sinks.html#autotoc_md66',1,'CLI Flag'],['../output-sinks.html#autotoc_md72',1,'CLI Flag']]],
  ['cmake_20fetchcontent_9',['CMake FetchContent',['../setup.html#setup-fetchcontent',1,'']]],
  ['command_20line_20interface_10',['Command Line Interface',['../cli.html',1,'']]],
  ['comparison_11',['Comparison',['../customize.html#autotoc_md37',1,'Absolute Comparison'],['../customize.html#autotoc_md35',1,'IEEE Comparison'],['../customize.html#autotoc_md36',1,'Relative Comparison']]],
  ['compile_20time_20discipline_12',['Compile-Time Discipline',['../compile-time.html',1,'']]],
  ['compilers_13',['Supported Compilers',['../index.html#autotoc_md40',1,'']]],
  ['computing_20ulp_14',['Computing ULP',['../rationale.html#ulp-computing',1,'']]],
  ['contributors_15',['New Contributors',['../changelog.html#autotoc_md9',1,'']]],
  ['control_16',['Execution Control',['../cli.html#autotoc_md31',1,'']]],
  ['cordelia_20gray_17',['Version 2.1 - Cordelia Gray',['../changelog.html#autotoc_md17',1,'']]],
  ['cost_18',['cost',['../compile-time.html#compile-time-cost',1,'Avoided headers and their cost'],['../compile-time.html#compile-time-comparison-include',1,'Minimal include cost']]],
  ['cost_20and_20crossings_19',['Fixed cost and crossings',['../compile-time.html#compile-time-comparison-fits',1,'']]],
  ['cost_20of_20a_20test_20suite_20',['Include cost of a test suite',['../compile-time.html#compile-time-why',1,'']]],
  ['cost_20of_20test_20cases_21',['Cost of test cases',['../compile-time.html#compile-time-comparison-cases',1,'']]],
  ['cpm_22',['Setup with CPM',['../setup.html#setup-cpm',1,'']]],
  ['crashed_20and_20stuck_20runs_23',['Crashed and Stuck Runs',['../customize.html#customize-abort',1,'']]],
  ['crossings_24',['Fixed cost and crossings',['../compile-time.html#compile-time-comparison-fits',1,'']]],
  ['customizing_20tts_20behaviour_25',['Customizing TTS Behaviour',['../customize.html',1,'']]]
];
