version: 2.0

jobs:
  clang:
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: . .circleci/prepare.sh
      - run:
          name: Install clang-9
          command: 'apt-get update && sudo apt-get install -y clang-9 && sudo apt-get install -y libstdc++-9-dev'
      - run:
          name: Running tests
          command: . .circleci/run.sh clang++-9

  gcc:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: . .circleci/prepare.sh
      - run:
          name: Running tests
          command: . .circleci/run.sh g++

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc
      - clang
