##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    permissions:
      contents: write
    uses: jfalcou/copacabana/.github/workflows/documentation.yml@184770e42deec34dc0cc39158960bb3acbbbd06e # v1
    with:
      project: tts
      coverage: true
