##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Prepare TTS
        run: |
          mkdir build && cd build
          cmake .. -G Ninja -DTTS_BUILD_TEST=OFF -DTTS_BUILD_DOCUMENTATION=ON

      - name: Generate Doxygen
        run: |
          cd build
          ninja doxygen

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
