##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: tts-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@184770e42deec34dc0cc39158960bb3acbbbd06e # v1
    with:
      project: tts
