##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Integration Tests
on:
  pull_request:
    branches:
      - main

concurrency:
  group: tts-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:

  install:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Install TTS from checkout
        run: |
          mkdir build && cd build
          cmake -G Ninja .. -DTTS_BUILD_TEST=OFF
          ninja install
      - name: Run Sample CMake
        run: |
          mkdir install && cd install
          cmake ../test/integration/install-test -G Ninja
          ninja && ctest --verbose
