##======================================================================================================================
##  TTS - Tiny Test System
##  Copyright : TTS Contributors & Maintainers
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: TTS Standalone Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    permissions:
      contents: write
      pull-requests: write
    uses: jfalcou/copacabana/.github/workflows/package-standalone.yml@184770e42deec34dc0cc39158960bb3acbbbd06e # v1
    with:
      project: tts
